website/blog/2019-02-08-Introducing-swc-1.0.md

docs(blog): fixed typo in the React (with jsx) example

---

website/core/Footer.js

The footer's 'introduction' link currently goes to a page that doesn't exist.
In the header, introduction goes to installation.
That's why I have replaced the link to be installation.

Replace broken introduction footer link

---

website/blog/2019-02-08-Introducing-swc-1.0.md
website/blog/2020-08-07-swc-1.2.13.md
website/src/components/GithubButton/index.tsx
website/src/components/HomeSplash/index.tsx
website/src/components/IndexPage/index.tsx
website/src/pages/index.tsx

I found that if I run the production build commands locally there's a breakage caused in the `GithubButton`.
Because the import relies on `window`, this is not present during server side rendering and causes the build to fail.  I've wrapped it up into an async import so that this no longer fails.
There was also a failure because two items were in the `pages` folder that should have been in `components`, so I've fixed that too.
Finally, there were a couple of broken links in the the blog posts and I've fixed them up too.

Bugfix -> server side rendering and broken links

---

website/docs/usage-swc-cli.md

- Add the SWC CLI options on the documentation website, all options were picked from [cli/swc/options.ts](https://github.com/swc-project/cli/blob/master/src/swc/options.ts)
Notes: some of examples were still in `// TODO` since I am not sure how to create an example.
I can fix that if someone can guide me how to do that.
But if no one can help on this, I think this version should be enough for initial documentation

docs: add cli options in website

---

src/components/Repl/index.tsx
src/components/Repl/urlHash.ts

[As the prettier playground does](https://prettier.io/playground/), I make Repl save Repl State(code, and config) as URL hash, and restore Repl State from urlhash on load.
Screen movie:
https://user-images.githubusercontent.com/42742053/129433578-3ee9e364-ca1e-4e83-b2dd-291360d118c6.mov
if a reporter can make a reproducible repl state and share its URL, we can reproduce it just by clicking that’s URL, so this function will make it easier to report and reproduce issues.
If you don’t think it is necessary, please be free to close this PR.

Feature proposal: Repl State as URLHash

---

src/components/Repl/index.tsx

Fix: https://github.com/swc-project/swc/issues/2151
Some error message from swc breaks REPL and the page turn white. ErrorMessage state on REPL should be string | null,  error messages from swc could be string | Error, so React will be broken due to mismatch state type. I fixed it by stringify error before setState.

Fix: broken Repl with some error from swc

---

docs/configuring-swc.md
docs/usage-spack-cli.md

The relative link will lead to create sub path under current path. e.g. `./config-js-minify` will become `/docs/configuring-swc/config-js-minify`. Convert them to abosulte paths

fix: broken doc links

---

docs/configuring-swc.md
docs/usage-swc-loader.md

@kdy1 I have proposed quite a few changes here, please let me know your thoughts and I will try to respond to feedback fully. 🙏 
My overall goal is to provide additional context for each configuration property and to reduce the assumption that the reader already knows how Babel works before using swc.
The result is more verbose, but with greater clarity and so it will be quicker to understand and move on despite there being more words on the page.
I would like to follow-up on this and improve clarity on some other properties such as `keepClassNames` and `paths` and `baseUrl` - and to add a few words on the sections which currently only contain a code snippet such as `jsc.parser`.

Update configuring swc doc

---

docs/configuring-swc.md

The name of this option is not the same as in the code: https://github.com/swc-project/swc/blob/master/node-swc/src/types.ts#L429

Fix typo in inlineSourcesContent option name

---

pages/index.mdx

Or should we add`/blog` to `redirects` in `next.config.js` ?

Fix address of blog link

---

next.config.js

Currently, the swc project's README incorrectly points to https://swc.rs/docs/comparison-babel for a Babel comparison.
The link should point to https://swc.rs/docs/migrating-from-babel
The broken link can either be resolved via redirect here or by changing the link in the README. I have made pull requests for both and will create an issue in the main project repo linking to those pull requests.

Add redirect for broken Babel comparison link

---

pages/playground/index.md

In Chrome, a website should specify the `allow` policy to allow cross-origin websites in iframe to write clipboard.
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes
https://web.dev/async-clipboard/#permissions-policy-integration
Currently, pushing `share button` causes DOMException Error with the stable chrome.

Fix: allow playground iframe to write clipboard

---

pages/docs/usage/plugins.md

I didn't want to open a PR for a single letter typo but I must admit I couldn't let it pass too.

Typo in plugins.md

---

pages/docs/configuration/minification.mdx

Related to https://github.com/swc-project/swc/pull/3476
Updates the mangler options for minification to include `reserved` option.

Add reserved option to mangler docs

---

styles.css

It fixes benchmarks's select button background color when dark mode is on.
Before:
After:

Fix Benchmarks Select Background Color

---

pages/docs/usage/core.md

documenting `parse` functions
I read the d.ts file that found out these functions

docs(core): add parse functions

---

pages/docs/usage/core.mdx

The parse deprecated options were removed.

docs(core): add type declarations

---

pages/docs/usage/swc-loader.md

Add that the parseMap option must be set when swc-loader and babel-loader are used together.
preview: https://website-ljc123qxn-swc-project.vercel.app/docs/usage/swc-loader#with-babel-loader
reference: https://github.com/swc-project/swc-loader/pull/13

docs(): Add documentation for use with babel-loader

---

theme.config.js

Seems [`projectLink`](https://nextra.vercel.app/themes/docs/configuration#projectlink) is recommended option, not `github`.

Fix GitHub icon link to not target shuding/nextra

---

pages/docs/configuration/supported-browsers.mdx
pages/docs/configuration/swcrc.mdx

Fixes https://github.com/swc-project/swc/issues/1606 and https://github.com/swc-project/swc/issues/4612.
Documents the behavior of `coreJs`.

Docs: `env.coreJs` usage

---

pages/docs/configuration/modules.mdx

Using JSON schema helps with configuring SWC in IDEs that support schema completion

show an example of using the schema field

---

package.json
pages/index.mdx
pnpm-lock.yaml

[Issue #168 Website is not Mobile Responsive](https://github.com/swc-project/website/issues/168)
[Issue #174 validateDOMNesting warning](https://github.com/swc-project/website/issues/174)
Updating Nextra to alpha.56 fixes the responsiveness
Wrapping the p tags in {} removes the console warning
Also note I have changed the wrapper for the community stars and downloads from a p tag to div.
If this is unwanted then let me know and I'll remove 👍 
---
- Closes #168
- Closes #174

Fix mobile responsiveness, Fix validateDOMNesting warning

---

pages/blog/swc-1.mdx
pages/docs/usage/cli.md
pages/docs/usage/swc-loader.md

Jest example is showing npm and yarn option. Might help others if this is shown in all examples.

docs: align install commands for examples

---

pages/docs/configuration/supported-browsers.mdx

Update the outdated documentation about `browserlist`:
- swc no longer requires the `browserlist` package to be installed as swc uses a rust-powered browserlist parser
- swc currently read neither `.browserlistrc` nor `package.json` for `targets`. It has to be configured manually.

docs(target): update browserlist section

---

pages/docs/configuration/compilation.md

The current examples, e.g `".*.js$"` can match a file named `index.js` but also a file named `indexjs` (without the extension), this is a minor thing but it's not the ideal regex to match against unless the dot is escaped.

[Docs] Update regex examples in configuration/compilation

---

pages/docs/configuration/minification.mdx

`keepClassnames` not working. `keepClassNames` is the correct one. Received error:
```
unknown field `keepClassnames`, expected one of `props`, `topLevel`, `keepClassNames`, `keepFnNames`, `keepPrivateProps`, `ie8`, `safari10`, `reserved`
```

Fix property name in minification mangle

---

pages/docs/configuration/minification.mdx

Follow-up on #206 . `keepFnNames` and `props` instead of `keepFnNames` and `properties`. Previously I received error:
```
unknown field `keepClassnames`, expected one of `props`, `topLevel`, `keepClassNames`, `keepFnNames`, `keepPrivateProps`, `ie8`, `safari10`, `reserved`
```

Fix property names in minification mangle

---

pages/docs/getting-started.mdx

With **pnpm** to install new packages `pnpm add` should be used. [pnpm doc](https://pnpm.io/cli/add)

fix add new packages with pnpm in "getting-started.mdx"

---

pages/docs/configuration/compilation.md

Listing "automatic" as the first enum value led me to think it was the default value, because no default value was documented. 
But the default value is "classic" according to the v1 code here: https://github.com/swc-project/swc/blob/main/crates/swc_ecma_transforms_react/src/jsx/mod.rs#L40
I think it's valuable to document the default value. Default values are documented for other options.

docs: mention default JSX runtime is "classic"

---

pages/docs/configuration/compilation.md

env.mode is false by default and could take false as a param, probably, its good to tell about that explicidly

Update env.mode options in compilation.md

---

pages/docs/usage/cli.mdx

Related to [this PR](https://github.com/swc-project/cli/pull/283) 
This PR introduces the `strip-leading-paths` command to the `cli` section on the docs.  This was a recent change and was undocumented in the docs, but very important.

feat: updates CLI docs adding new `strip-leading-paths` parameter

---

pages/docs/configuration/compilation.mdx

Based on the following error:
```sh
[Error: failed to handle: base_dir(`.`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details.
```
Added to docs to ensure that the baseUrl must be absolute.

docs: ensure that the baseUrl must be an absolute path

---

pages/index.mdx

On the section, It provides same Twitter link in duplicate so I changed it to GitHub link for providing more information of creator.

feat(/): change link from Twitter to GitHub

---

pages/docs/usage/swc-loader.mdx

Add a tip  for using Rspack builtin:swc-loader with SWC
> For Rspack users, you can use Rspack's [builtin:swc-loader](https://rspack.dev/guide/features/builtin-swc-loader), without the need to install the swc-loader package.

docs: add tip for Rspack builtin:swc-loader

---

pages/docs/usage/core.mdx

Hey folks! 👋
https://github.com/swc-project/swc/pull/9026 added a new value to the `module` property in `JSMinifyOptions`, but the type declaration in `core.mdx` was not updated.
This change fixes that.
Please let me know if I missed anything!

core.mdx: Add "unknown" value to JSMinifyOptions module

---

pages/docs/usage/bundling.mdx

The `cli` package and its examples was moved. This PR fixes the link to its new location.

fix: link to bundling example using spack

---

pages/docs/references/wasm-typescript.mdx

URL: https://swc.rs/docs/references/wasm-typescript
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img width="734" alt="Screenshot 2024-07-29 at 14 35 12" src="https://github.com/user-attachments/assets/0f8d4662-3538-4322-ba49-8fce67f83101"></td>
<td><img width="734" alt="Screenshot 2024-07-29 at 14 35 29" src="https://github.com/user-attachments/assets/74acc3f1-f6f9-4f91-8cf8-24cad96cb128">
</td>
</tr>
</table>

docs: fix typo in @swc/wasm-typescript

---

pages/docs/plugin/ecmascript/getting-started.mdx

Fix for initialising the `Ident` without a `SyntaxContext`.

fix: plugin starter Ident init

---

pages/index.mdx

It should be `pnpm add <pkg>` instead of `pnpm install <pkg>`.
`pnpm install` is used to install all dependencies for a project while `pnpm add <pkg>` is used to install a package and any packages that it depends on.
More info (official source):
- https://pnpm.io/cli/add
- https://pnpm.io/cli/install
---
`pnpm install <pkg>` does the same as `pnpm add <pkg>` today, but it might stop functioning that way in future versions since the official docs clarify the difference between the two. It might be that `pnpm install <pkg>` was used in past versions, and the PNPM team didn't want to remove support for it right away after introducing `pnpm add <pkg>`.

fix(docs): use `pnpm add <pkg>` instead of `pnpm install <pkg>`

---

apps/website/package.json
pnpm-lock.yaml

The SWC website looks weird on devices that have Inter installed as their UI font because `nextra-theme-docs` enables the `ss06` font feature by default until version 2.2.15. this fixes that issue by bumping `nextra` to v2.2.20. resolves #247 
before
after

bump to nextra v2.2

---

apps/website/content/docs/usage/cli.mdx

Wrap double dash (--) arguments with code block prevents replacing it with joined character on website + improves consitency with existing '--only' argument
Spent good 5 min figuring out why copy-pasted argument from official docs doesn't work, until noticed that double dash magically transformed into the single long dash character (possibly markdown lib bug)

fix: double dash arguments in cli.mdx

---

apps/website/content/docs/configuration/compilation.mdx

Update `jsx.transform.react.runtime` option, add `'preserve'` option and clarify usage of each runtime mode.
Ref: https://github.com/swc-project/swc/issues/9929

docs: update `jsx.transform.react.runtime` option
