swc-project/website

- docs/configuring-swc.md
Add _use_ to make the sentence complete
> add verb to sentence

- docs/configuring-preset-env.md
> Fix typo in configuring-preset-env.md

- website/docs/configuring-preset-env.md
This documents path the option added in swc-project/swc#1374
> Document path option for preset-env

- docs/configuring-preset-env.md
Enable all trnasforms -> Enable all transforms
> Fix typo in `preset-env.forceAllTransforms` docs

- docs/config-js-minify.md
- fix broken link of `yarn`
- fix broken code block
> docs: format doc

- docs/benchmark-transform.md
> chore: update the note

- src/css/custom.css
fix [swc-project/swc#1705](https://github.com/swc-project/swc/issues/1705)
> chores: change nav bar menu link color

- docs/usage-plugin.md
Here is a proposal for a more up-to-date version of the plugin docs.
I ~stole~ borrowed some parts from the awesome https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md
Please let me know what you think - I am very open for adjusting it depending on what you have in mind with this page  :)
> Improve plugin docs

- pages/index.mdx
> Temporarily remove crates badge to fix layout shift

- pages/docs/configuration/swcrc.mdx
fix: update link to minification configuration
> fix: update link to minification configuration

- pages/docs/usage/plugins.md
fixed the Visitor import methods.
refer to: https://github.com/swc-project/swc/pull/2291
> fix(doc): fixed the Visitor import methods.

- pages/docs/configuration/compilation.md
Docs update following https://github.com/swc-project/swc/pull/3815
Will be valid post `v1.2.153` milestone release
> feat(docs): Add preserveAllComments feature flag documentation

- pages/docs/plugin/publishing.mdx
"yout" should be "your" and "traicing" should be "tracing".
> Fix small typos in docs

- next.config.js
- package.json
- pages/_app.js
- pages/index.mdx
- pages/meta.json
- pages/playground/index.md
- pages/playground/meta.json
- pnpm-lock.yaml
- theme.config.js
- Make https://website-git-fork-shuding-patch-1-swc-project.vercel.app/playground full-width
- Enable the new search
This closes #133 as well.
> Upgrade Nextra, enable new search, make /playground full-width

- pages/docs/usage/cli.md
> docs: fix syntax highlighting

- pages/docs/plugin/ecmascript/getting-started.mdx
- resolve #186 
- Adding a simple example of test
> fix: Plugin's getting-started.mdx modified and test added

- pages/docs/configuration/swcrc.mdx
Just noticed this and clicked the edit button 🤷
> Correct tiny "automatically" typo

- pages/docs/migrating-from-babel.md
Support added in https://github.com/swc-project/swc/pull/3225
> Update status for logical-assignment-operators

- pages/docs/usage/jest.mdx
transformer is `string | [string, Record<string, unknown>]`
https://github.com/facebook/jest/blob/59cf4e39ba1c0e2675085a937d69131adea273d8/packages/jest-types/src/Config.ts#L315-L317 
https://github.com/facebook/jest/blob/59cf4e39ba1c0e2675085a937d69131adea273d8/packages/jest-types/src/Config.ts#L143
> Fix jest transform

- pages/docs/plugin/ecmascript/cheatsheet.mdx
Heyo 👋
This is a simple PR fixing a small typo in the docs.
Love the project btw, i'm currently migrating all the https://nullstack.app loaders to swc 💜
> :pencil2: :memo: fix struct typo

- pages/docs/configuration/minification.mdx
Fix typo "delcared" -> "declared"
> minification.mdx: Typo fix

- pages/blog/perf-swc-vs-babel.mdx
I guess I don't know the type of `promises`, but I'm guessing it is supposed to be `Promise<void>[]`
> fix: use "for of" loop

- pages/docs/migrating-from-tsc.md
I am not a native English speaker. please improve any inadequacies as you see fit.
> Add more info for tsc

- pages/docs/configuration/minification.mdx
Update `minification.mdx`. Just a tiny thing...
> chore: fix typo in minifcation -> minification

- pages/docs/configuration/minification.mdx
Ref: https://github.com/swc-project/swc/pull/6703/files
> Fix default comments options for minify

- pages/docs/configuration/modules.mdx
Add `resolveFully` to swc docs (as completed here https://github.com/swc-project/swc/pull/7901)
> add resolveFully jsc.module options

- pages/docs/configuration/compilation.mdx
Related to  https://github.com/swc-project/swc/issues/8425
> Add loose mode warning

- pages/docs/usage/jest.mdx
Update `@swc/jest` docs based on the last commit from jest package: https://github.com/swc-project/pkgs/blob/2ab0d03ff9bc9f46913c51870ac9f068b662e460/packages/jest/README.md
> docs(jest): update usage guide

- pages/docs/configuration/minification.mdx
Closes https://github.com/swc-project/website/issues/258
> docs: update minification docs to mention swc-minify-webpack-plugin

- pages/docs/usage/swc-loader.mdx
Had to learn this the hard way. 😅
> swc-loader: note how `options` work

- apps/website/theme.config.js
> Fix docsRepositoryBase in theme.config.js

- apps/website/pages/docs/configuration/compilation.mdx
- add `jsc.experimental.cacheRoot`
- rename `jsc.experimental.keepImportAssertions ` to `jsc.experimental.keepImportAttributes`
> docs: update jsc.experimental configuration
